server:
  port: 9090
spring:
  datasource:
    data-password: 
    data-username: sa
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
      
